package org.processmining.lifecycleperformance.models.preprocessors;

public abstract class AssignActivityInstanceXLogPreprocessorStrategy implements IAssignActivityInstanceXLogPreprocessorStrategy {

}
